#pragma once
#include <iostream>
#include <cstdint>

typedef uint64_t GLuint64;
typedef char GLchar;
typedef ptrdiff_t GLintptr;

#define FF_TEXTURE_TARGET_GL_TEXTURE_1D 0x0DE0
#define FF_TEXTURE_TARGET_GL_TEXTURE_2D 0x0DE1
#define FF_TEXTURE_TARGET_GL_TEXTURE_3D 0x806F
#define FF_TEXTURE_TARGET_GL_TEXTURE_CUBE_MAP 0x8513
#define FF_TEXTURE_TARGET_GL_TEXTURE_CUBE_MAP_POSITIVE_X 0x8515
#define FF_TEXTURE_TARGET_GL_TEXTURE_CUBE_MAP_NEGATIVE_X 0x8516
#define FF_TEXTURE_TARGET_GL_TEXTURE_CUBE_MAP_POSITIVE_Y 0x8517
#define FF_TEXTURE_TARGET_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 0x8518
#define FF_TEXTURE_TARGET_GL_TEXTURE_CUBE_MAP_POSITIVE_Z 0x8519
#define FF_TEXTURE_TARGET_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 0x851A

#define FF_PIXEL_FORMAT_GL_RGBA 0x1908
#define FF_PIXEL_FORMAT_GL_RGB 0x1907
#define FF_PIXEL_FORMAT_GL_RED 0x1903
#define FF_PIXEL_FORMAT_GL_GREEN 0x1904
#define FF_PIXEL_FORMAT_GL_BLUE 0x1905
#define FF_PIXEL_FORMAT_GL_ALPHA 0x1906
#define FF_PIXEL_FORMAT_GL_DEPTH_COMPONENT 0x1902
#define FF_PIXEL_FORMAT_GL_DEPTH_STENCIL 0x84F9

#define FF_INTERNAL_FORMAT_GL_RGB16F 0x881B                    
#define FF_INTERNAL_FORMAT_GL_RGB32F 0x8815                     
#define FF_INTERNAL_FORMAT_GL_RGBA16F 0x881A                    
#define FF_INTERNAL_FORMAT_GL_RGBA32F 0x8814                    
#define FF_INTERNAL_FORMAT_GL_R16F 0x822D                      
#define FF_INTERNAL_FORMAT_GL_R32F 0x822E                       
#define FF_INTERNAL_FORMAT_GL_RG16F 0x822F                      
#define FF_INTERNAL_FORMAT_GL_RG32F 0x8230   

#define FF_TEXTURE_WRAP_MODE_GL_REPEAT 0x2901
#define FF_TEXTURE_WRAP_MODE_GL_MIRRORED_REPEAT 0x8370
#define FF_TEXTURE_WRAP_MODE_GL_CLAMP_TO_EDGE 0x812F
#define FF_TEXTURE_WRAP_MODE_GL_CLAMP_TO_BORDER 0x812D

#define FF_TEXTURE_FILTER_MODE_GL_NEAREST 0x2600
#define FF_TEXTURE_FILTER_MODE_GL_LINEAR 0x2601
#define FF_TEXTURE_FILTER_MODE_GL_NEAREST_MIPMAP_NEAREST 0x2700
#define FF_TEXTURE_FILTER_MODE_GL_LINEAR_MIPMAP_NEAREST 0x2701
#define FF_TEXTURE_FILTER_MODE_GL_NEAREST_MIPMAP_LINEAR 0x2702
#define FF_TEXTURE_FILTER_MODE_GL_LINEAR_MIPMAP_LINEAR 0x2703

#define FF_DATA_TYPE_GL_BYTE 0x1400
#define FF_DATA_TYPE_GL_UNSIGNED_BYTE 0x1401
#define FF_DATA_TYPE_GL_SHORT 0x1402
#define FF_DATA_TYPE_GL_UNSIGNED_SHORT 0x1403
#define FF_DATA_TYPE_GL_INT 0x1404
#define FF_DATA_TYPE_GL_UNSIGNED_INT 0x1405
#define FF_DATA_TYPE_GL_FLOAT 0x1406
#define FF_DATA_TYPE_GL_DOUBLE 0x140A

#define FF_BUFFER_TYPE_GL_ARRAY_BUFFER 0x8892
#define FF_BUFFER_TYPE_GL_ELEMENT_ARRAY_BUFFER 0x8893
#define FF_BUFFER_USAGE_GL_STATIC_DRAW 0x88E4
#define FF_BUFFER_USAGE_GL_DYNAMIC_DRAW 0x88E8

#define FF_SHADER_TYPE_GL_VERTEX_SHADER 0x8B31
#define FF_SHADER_TYPE_GL_FRAGMENT_SHADER 0x8B30
#define FF_SHADER_TYPE_GL_GEOMETRY_SHADER 0x8DD9
#define FF_SHADER_TYPE_GL_TESS_CONTROL_SHADER 0x8E88
#define FF_SHADER_TYPE_GL_TESS_EVALUATION_SHADER 0x8E87
#define FF_SHADER_TYPE_GL_COMPUTE_SHADER 0x91B9

#define FF_SHADER_PROGRAM_UNUSEABLE 0
#define FF_SHADER_PROGRAM_LINKED 1
#define FF_SHADER_PROGRAM_LINK_FAILED 2

#define FF_FRAMEBUFFER_ATTACHMENT_COLOR0 0x8CE0
#define FF_FRAMEBUFFER_ATTACHMENT_DEPTH 0x8D00
#define FF_FRAMEBUFFER_ATTACHMENT_STENCIL 0x8D20
#define FF_FRAMEBUFFER_ATTACHMENT_DEPTH_STENCIL 0x821A

#define FF_GL_FRAMEBUFFER 0x8D40
#define FF_FRAMEBUFFER_COMPLETE 0x8CD5
#define FF_FRAMEBUFFER_UNDEFINED 0x8219
#define FF_FRAMEBUFFER_INCOMPLETE_ATTACHMENT 0x8CD6
#define FF_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT 0x8CD7
#define FF_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER 0x8CDB
#define FF_FRAMEBUFFER_INCOMPLETE_READ_BUFFER 0x8CDC
#define FF_FRAMEBUFFER_UNSUPPORTED 0x8CDD
#define FF_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE 0x8D56
#define FF_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS 0x8DA8

#define FF_PRIMITIVE_TYPE_GL_POINTS 0x0000
#define FF_PRIMITIVE_TYPE_GL_LINES 0x0001
#define FF_PRIMITIVE_TYPE_GL_LINE_STRIP 0x0003
#define FF_PRIMITIVE_TYPE_GL_LINE_LOOP 0x0002
#define FF_PRIMITIVE_TYPE_GL_TRIANGLES 0x0004
#define FF_PRIMITIVE_TYPE_GL_TRIANGLE_STRIP 0x0005
#define FF_PRIMITIVE_TYPE_GL_TRIANGLE_FAN 0x0006
#define FF_PRIMITIVE_TYPE_GL_LINES_ADJACENCY 0x000A
#define FF_PRIMITIVE_TYPE_GL_LINE_STRIP_ADJACENCY 0x000B
#define FF_PRIMITIVE_TYPE_GL_TRIANGLES_ADJACENCY 0x000C
#define FF_PRIMITIVE_TYPE_GL_TRIANGLE_STRIP_ADJACENCY 0x000D
#define FF_PRIMITIVE_TYPE_GL_PATCHES 0x000E

#define FF_BLEND_MODE_GL_ZERO 0
#define FF_BLEND_MODE_GL_ONE 1
#define FF_BLEND_MODE_GL_SRC_COLOR 0x0300
#define FF_BLEND_MODE_GL_ONE_MINUS_SRC_COLOR 0x0301
#define FF_BLEND_MODE_GL_DST_COLOR 0x0306
#define FF_BLEND_MODE_GL_ONE_MINUS_DST_COLOR 0x0307
#define FF_BLEND_MODE_GL_SRC_ALPHA 0x0302
#define FF_BLEND_MODE_GL_ONE_MINUS_SRC_ALPHA 0x0303
#define FF_BLEND_MODE_GL_DST_ALPHA 0x0304
#define FF_BLEND_MODE_GL_ONE_MINUS_DST_ALPHA 0x0305
#define FF_BLEND_MODE_GL_CONSTANT_COLOR 0x8001
#define FF_BLEND_MODE_GL_ONE_MINUS_CONSTANT_COLOR 0x8002
#define FF_BLEND_MODE_GL_CONSTANT_ALPHA 0x8003
#define FF_BLEND_MODE_GL_ONE_MINUS_CONSTANT_ALPHA 0x8004
#define FF_BLEND_MODE_GL_SRC_ALPHA_SATURATE 0x0308
#define FF_BLEND_MODE_GL_SRC1_COLOR 0x88F9
#define FF_BLEND_MODE_GL_ONE_MINUS_SRC1_COLOR 0x88FA
#define FF_BLEND_MODE_GL_SRC1_ALPHA 0x8589
#define FF_BLEND_MODE_GL_ONE_MINUS_SRC1_ALPHA 0x88FB

#define FF_CLEAR_BUFFER_BIT_GL_COLOR_BUFFER_BIT 0x00004000
#define FF_CLEAR_BUFFER_BIT_GL_DEPTH_BUFFER_BIT 0x00000100
#define FF_CLEAR_BUFFER_BIT_GL_STENCIL_BUFFER_BIT 0x00000400

#define FF_COMPARE_FUNC_GL_NEVER 0x0200
#define FF_COMPARE_FUNC_GL_LESS 0x0201
#define FF_COMPARE_FUNC_GL_EQUAL 0x0202
#define FF_COMPARE_FUNC_GL_LEQUAL 0x0203
#define FF_COMPARE_FUNC_GL_GREATER 0x0204
#define FF_COMPARE_FUNC_GL_NOTEQUAL 0x0205
#define FF_COMPARE_FUNC_GL_GEQUAL 0x0206
#define FF_COMPARE_FUNC_GL_ALWAYS 0x0207

#define FF_STENCIL_OP_GL_KEEP 0x1E00
#define FF_STENCIL_OP_GL_ZERO 0
#define FF_STENCIL_OP_GL_REPLACE 0x1E01
#define FF_STENCIL_OP_GL_INCR 0x1E02
#define FF_STENCIL_OP_GL_INCR_WRAP 0x8507
#define FF_STENCIL_OP_GL_DECR 0x1E03
#define FF_STENCIL_OP_GL_DECR_WRAP 0x8508
#define FF_STENCIL_OP_GL_INVERT 0x150A

#define FF_BLEND_EQUATION_GL_FUNC_ADD 0x8006
#define FF_BLEND_EQUATION_GL_FUNC_SUBTRACT 0x800A
#define FF_BLEND_EQUATION_GL_FUNC_REVERSE_SUBTRACT 0x800B
#define FF_BLEND_EQUATION_GL_MIN 0x8007
#define FF_BLEND_EQUATION_GL_MAX 0x8008

#define FF_FRONT_FACE_GL_CW 0x0900
#define FF_FRONT_FACE_GL_CCW 0x0901

#define FF_CULL_FACE_MODE_GL_FRONT 0x0404
#define FF_CULL_FACE_MODE_GL_BACK 0x0405
#define FF_CULL_FACE_MODE_GL_FRONT_AND_BACK 0x0408

#define FF_ENABLE_DISABLE_GL_TRUE 1
#define FF_ENABLE_DISABLE_GL_FALSE 0

#define FF_ACTIVE_TEXTURE_GL_TEXTURE0 0x84C0
#define FF_DEPTH_FUNC_GL_ALWAYS 0x0207

#define FF_VERTEX_ATTRIB_TYPE_GL_BYTE 0x1400
#define FF_VERTEX_ATTRIB_TYPE_GL_UNSIGNED_BYTE 0x1401
#define FF_VERTEX_ATTRIB_TYPE_GL_SHORT 0x1402
#define FF_VERTEX_ATTRIB_TYPE_GL_UNSIGNED_SHORT 0x1403
#define FF_VERTEX_ATTRIB_TYPE_GL_INT 0x1404
#define FF_VERTEX_ATTRIB_TYPE_GL_UNSIGNED_INT 0x1405
#define FF_VERTEX_ATTRIB_TYPE_GL_FLOAT 0x1406
#define FF_VERTEX_ATTRIB_TYPE_GL_DOUBLE 0x140A

#define FF_ERROR_GL_NO_ERROR 0
#define FF_ERROR_GL_INVALID_ENUM 0x0500
#define FF_ERROR_GL_INVALID_VALUE 0x0501
#define FF_ERROR_GL_INVALID_OPERATION 0x0502
#define FF_ERROR_GL_STACK_OVERFLOW 0x0503
#define FF_ERROR_GL_STACK_UNDERFLOW 0x0504
#define FF_ERROR_GL_OUT_OF_MEMORY 0x0505
#define FF_ERROR_GL_INVALID_FRAMEBUFFER_OPERATION 0x0506

#define FF_TEXTURE_UNIT_GL_TEXTURE0 0x84C0
#define FF_TEXTURE_UNIT_GL_TEXTURE1 0x84C1
#define FF_TEXTURE_UNIT_GL_TEXTURE2 0x84C2
#define FF_TEXTURE_UNIT_GL_TEXTURE3 0x84C3
#define FF_TEXTURE_UNIT_GL_TEXTURE4 0x84C4
#define FF_TEXTURE_UNIT_GL_TEXTURE5 0x84C5
#define FF_TEXTURE_UNIT_GL_TEXTURE6 0x84C6
#define FF_TEXTURE_UNIT_GL_TEXTURE7 0x84C7
#define FF_TEXTURE_UNIT_GL_TEXTURE8 0x84C8
#define FF_TEXTURE_UNIT_GL_TEXTURE9 0x84C9
#define FF_TEXTURE_UNIT_GL_TEXTURE10 0x84CA
#define FF_TEXTURE_UNIT_GL_TEXTURE11 0x84CB
#define FF_TEXTURE_UNIT_GL_TEXTURE12 0x84CC
#define FF_TEXTURE_UNIT_GL_TEXTURE13 0x84CD
#define FF_TEXTURE_UNIT_GL_TEXTURE14 0x84CE
#define FF_TEXTURE_UNIT_GL_TEXTURE15 0x84CF

#define FF_LOGIC_OP_GL_CLEAR 0x1500
#define FF_LOGIC_OP_GL_SET 0x150F
#define FF_LOGIC_OP_GL_COPY 0x1503
#define FF_LOGIC_OP_GL_COPY_INVERTED 0x150C
#define FF_LOGIC_OP_GL_NOOP 0x1505
#define FF_LOGIC_OP_GL_INVERT 0x150A
#define FF_LOGIC_OP_GL_AND 0x1501
#define FF_LOGIC_OP_GL_NAND 0x150E
#define FF_LOGIC_OP_GL_OR 0x1507
#define FF_LOGIC_OP_GL_NOR 0x1508
#define FF_LOGIC_OP_GL_XOR 0x1506
#define FF_LOGIC_OP_GL_EQUIV 0x1509
#define FF_LOGIC_OP_GL_AND_REVERSE 0x1502
#define FF_LOGIC_OP_GL_AND_INVERTED 0x1504
#define FF_LOGIC_OP_GL_OR_REVERSE 0x150B
#define FF_LOGIC_OP_GL_OR_INVERTED 0x150D

#define FF_STENCIL_INDEX_GL_FRONT_AND_BACK 0x0408

#define FF_GL_FILL 0x1B02
#define FF_GL_LINE 0x1B01
#define FF_GL_POINT 0x1B00

#define FF_KEY_UNKNOWN              -1

#define FF_KEY_SPACE              32
#define FF_KEY_APOSTROPHE         39  /* ' */
#define FF_KEY_COMMA              44  /* , */
#define FF_KEY_MINUS              45  /* - */
#define FF_KEY_PERIOD             46  /* . */
#define FF_KEY_SLASH              47  /* / */
#define FF_KEY_0                  48
#define FF_KEY_1                  49
#define FF_KEY_2                  50
#define FF_KEY_3                  51
#define FF_KEY_4                  52
#define FF_KEY_5                  53
#define FF_KEY_6                  54
#define FF_KEY_7                  55
#define FF_KEY_8                  56
#define FF_KEY_9                  57
#define FF_KEY_SEMICOLON          59  /* ; */
#define FF_KEY_EQUAL              61  /* = */
#define FF_KEY_A                  65
#define FF_KEY_B                  66
#define FF_KEY_C                  67
#define FF_KEY_D                  68
#define FF_KEY_E                  69
#define FF_KEY_F                  70
#define FF_KEY_G                  71
#define FF_KEY_H                  72
#define FF_KEY_I                  73
#define FF_KEY_J                  74
#define FF_KEY_K                  75
#define FF_KEY_L                  76
#define FF_KEY_M                  77
#define FF_KEY_N                  78
#define FF_KEY_O                  79
#define FF_KEY_P                  80
#define FF_KEY_Q                  81
#define FF_KEY_R                  82
#define FF_KEY_S                  83
#define FF_KEY_T                  84
#define FF_KEY_U                  85
#define FF_KEY_V                  86
#define FF_KEY_W                  87
#define FF_KEY_X                  88
#define FF_KEY_Y                  89
#define FF_KEY_Z                  90
#define FF_KEY_LEFT_BRACKET       91  /* [ */
#define FF_KEY_BACKSLASH          92  /* \ */
#define FF_KEY_RIGHT_BRACKET      93  /* ] */
#define FF_KEY_GRAVE_ACCENT       96  /* ` */
#define FF_KEY_WORLD_1            161 /* non-US #1 */
#define FF_KEY_WORLD_2            162 /* non-US #2 */

#define FF_KEY_ESCAPE             256
#define FF_KEY_ENTER              257
#define FF_KEY_TAB                258
#define FF_KEY_BACKSPACE          259
#define FF_KEY_INSERT             260
#define FF_KEY_DELETE             261
#define FF_KEY_RIGHT              262
#define FF_KEY_LEFT               263
#define FF_KEY_DOWN               264
#define FF_KEY_UP                 265
#define FF_KEY_PAGE_UP            266
#define FF_KEY_PAGE_DOWN          267
#define FF_KEY_HOME               268
#define FF_KEY_END                269
#define FF_KEY_CAPS_LOCK          280
#define FF_KEY_SCROLL_LOCK        281
#define FF_KEY_NUM_LOCK           282
#define FF_KEY_PRINT_SCREEN       283
#define FF_KEY_PAUSE              284
#define FF_KEY_F1                 290
#define FF_KEY_F2                 291
#define FF_KEY_F3                 292
#define FF_KEY_F4                 293
#define FF_KEY_F5                 294
#define FF_KEY_F6                 295
#define FF_KEY_F7                 296
#define FF_KEY_F8                 297
#define FF_KEY_F9                 298
#define FF_KEY_F10                299
#define FF_KEY_F11                300
#define FF_KEY_F12                301
#define FF_KEY_F13                302
#define FF_KEY_F14                303
#define FF_KEY_F15                304
#define FF_KEY_F16                305
#define FF_KEY_F17                306
#define FF_KEY_F18                307
#define FF_KEY_F19                308
#define FF_KEY_F20                309
#define FF_KEY_F21                310
#define FF_KEY_F22                311
#define FF_KEY_F23                312
#define FF_KEY_F24                313
#define FF_KEY_F25                314
#define FF_KEY_KP_0               320
#define FF_KEY_KP_1               321
#define FF_KEY_KP_2               322
#define FF_KEY_KP_3               323
#define FF_KEY_KP_4               324
#define FF_KEY_KP_5               325
#define FF_KEY_KP_6               326
#define FF_KEY_KP_7               327
#define FF_KEY_KP_8               328
#define FF_KEY_KP_9               329
#define FF_KEY_KP_DECIMAL         330
#define FF_KEY_KP_DIVIDE          331
#define FF_KEY_KP_MULTIPLY        332
#define FF_KEY_KP_SUBTRACT        333
#define FF_KEY_KP_ADD             334
#define FF_KEY_KP_ENTER           335
#define FF_KEY_KP_EQUAL           336
#define FF_KEY_LEFT_SHIFT         340
#define FF_KEY_LEFT_CONTROL       341
#define FF_KEY_LEFT_ALT           342
#define FF_KEY_LEFT_SUPER         343
#define FF_KEY_RIGHT_SHIFT        344
#define FF_KEY_RIGHT_CONTROL      345
#define FF_KEY_RIGHT_ALT          346
#define FF_KEY_RIGHT_SUPER        347
#define FF_KEY_MENU               348

#define FF_GLFW_PRESS 1
#define FF_GLFW_RELEASE 0
#define FF_GLFW_REPEAT 2
#define FF_GLFW_KEY_UNKNOWN -1

#define FF_GLFW_MOUSE_BUTTON_1         0
#define FF_GLFW_MOUSE_BUTTON_2         1
#define FF_GLFW_MOUSE_BUTTON_3         2
#define FF_GLFW_MOUSE_BUTTON_4         3
#define FF_GLFW_MOUSE_BUTTON_5         4
#define FF_GLFW_MOUSE_BUTTON_6         5
#define FF_GLFW_MOUSE_BUTTON_7         6
#define FF_GLFW_MOUSE_BUTTON_8         7
#define FF_GLFW_MOUSE_BUTTON_LAST      FF_GLFW_MOUSE_BUTTON_8
#define FF_GLFW_MOUSE_BUTTON_LEFT      FF_GLFW_MOUSE_BUTTON_1
#define FF_GLFW_MOUSE_BUTTON_RIGHT     FF_GLFW_MOUSE_BUTTON_2
#define FF_GLFW_MOUSE_BUTTON_MIDDLE    FF_GLFW_MOUSE_BUTTON_3

#define FF_ATTACHMENT_COLOR_ATTACHMENT0 0x8CE0
#define FF_ATTACHMENT_COLOR_ATTACHMENT1 0x8CE1
#define FF_ATTACHMENT_COLOR_ATTACHMENT2 0x8CE2
#define FF_ATTACHMENT_COLOR_ATTACHMENT3 0x8CE3
#define FF_ATTACHMENT_COLOR_ATTACHMENT4 0x8CE4
#define FF_ATTACHMENT_COLOR_ATTACHMENT5 0x8CE5
#define FF_ATTACHMENT_COLOR_ATTACHMENT6 0x8CE6
#define FF_ATTACHMENT_COLOR_ATTACHMENT7 0x8CE7
#define FF_ATTACHMENT_COLOR_ATTACHMENT8 0x8CE8
#define FF_ATTACHMENT_COLOR_ATTACHMENT9 0x8CE9
#define FF_ATTACHMENT_COLOR_ATTACHMENT10 0x8CEA
#define FF_ATTACHMENT_COLOR_ATTACHMENT11 0x8CEB
#define FF_ATTACHMENT_COLOR_ATTACHMENT12 0x8CEC
#define FF_ATTACHMENT_COLOR_ATTACHMENT13 0x8CED
#define FF_ATTACHMENT_COLOR_ATTACHMENT14 0x8CEE
#define FF_ATTACHMENT_COLOR_ATTACHMENT15 0x8CEF

#define FF_ATTACHMENT_DEPTH_ATTACHMENT 0x8D00
#define FF_ATTACHMENT_STENCIL_ATTACHMENT 0x8D20
#define FF_ATTACHMENT_DEPTH_STENCIL_ATTACHMENT 0x821A

